### ISSUE TITLE
use addon on M1 Mac mini with OF 0.11.2

### ISSUE THREAD

**Issue by stephanschulz** [moostrik/ofxPvAPI#1]
This is a great addon and it works great on macOS 10.15.7, OF 0.11.0, Xcode 12.4, architecture x86_64.

But I am now trying to make it work on a M1 Mac mini.

OF 0.11.0 can not be used on M1 any more, so I have to use OF 0.11.2.
Trying to compile your addon with OF 0.11.2 on macOS 10.15.7 or 11.4 both throw errors like this:

It seems to be all about `Undefined symbols for architecture arm64:`
<img width="1133" alt="Screen Shot 2021-08-04 at 1 31 28 PM" src="https://user-images.githubusercontent.com/1054816/128227415-e3c1c369-d60e-4759-acc7-c044de1a8ccc.png">

Do you think the `libPvAPI.dylib` is not made for the new M1 architecture since it is an AVT legacy product?

Luckily I can compile my app on macOS 10.15 with OF 0.11.0 and then copy it over to the M1 Mac mini and it work. But I really hope to be able to compile directly on the M1.

Thanks for any advice.

**Comment by stephanschulz** [comment]
Using `./CLipConfig -l` as discussed here works on the M1:
https://www.alliedvision.com/fileadmin/content/documents/products/cameras/various/installation-manual/GigE_Installation_Manual.pdf

**Comment by stephanschulz** [comment]
I contacted AVT and this is their response:

Unfortunately, PvAPI is not available for ARM based MacOS systems, nor is it being further developed.
We have not ported Vimba to MacOS, only Windows and Linux.

At this time, I'd have to suggest trying an open source project called Aravis.

https://github.com/AravisProject/aravis

**Comment by moostrik** [comment]
I knew for I while they were not going to support Mac anymore, so I created a new Addon for linux [ofxVimba](https://github.com/moostrik/ofxVimba)
Thanks for the Aravis tip!

**Comment by stephanschulz** [comment]
Yes I saw ofxVimba the other day. Looks promising. 
Do you know if it would work on newer macOS systems?

**Comment by moostrik** [comment]
Unfortunately it only works on Linux (tested on Ubuntu) and should work on Windows (not tested recently)
